/* tslint:disable */
/* eslint-disable */
/**
 * Posts API Swagger
 * The Posts API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePostDto
 */
export interface UpdatePostDto {
    /**
     * 게시글 제목
     * @type {string}
     * @memberof UpdatePostDto
     */
    'title'?: string;
    /**
     * 게시글 본문
     * @type {string}
     * @memberof UpdatePostDto
     */
    'content'?: string;
}

